---
- name: Ensure Sublime Text directories exist.
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ sublime_base_path }}/{{ sublime_config_path }}"
    - "{{ sublime_base_path }}/Installed Packages"

- name: Ensure Sublime Package Control is installed.
  get_url:
    url: "https://packagecontrol.io/Package%20Control.sublime-package"
    dest: "{{ sublime_base_path }}/Installed Packages/Package Control.sublime-package"

- name: Ensure subl command available for use.
  blockinfile:
    path: ~/.zshrc
    state: present
    block: |
      ###############################################################################
      # SUBLIME TEXT SUBL CMD
      ###############################################################################

      export PATH="/Applications/Sublime Text.app/Contents/SharedSupport/bin:$PATH"

- name: Ensure Sublime Package Control Packages are configured.
  template:
    src: ../templates/Package_Control.sublime-settings.j2
    dest: "{{ sublime_base_path }}/{{ sublime_config_path }}/Package Control.sublime-settings"

- name: Copy Sublime Text Preferences
  copy:
    src: ../templates/Preferences.sublime-settings
    dest: "{{ sublime_base_path }}/{{ sublime_config_path }}/Preferences.sublime-settings"

- name: Setup Sublime Text mouse bindings
  template:
    src: "../templates/Default (OSX).sublime-mousemap.j2"
    dest: "{{ sublime_base_path }}/{{ sublime_config_path }}/Default (OSX).sublime-mousemap"
